import Head from 'next/head'
import TitleSection from '../../components/utils/TitleSection'
import Container from '@mui/material/Container'
import Box from '@mui/material/Box'
import { NextPage } from 'next'
import Appointments from '../../components/appointments/Appointments'


const TurnosPage: NextPage = () => {
  return (
    <>
      {/*  <Head>
        <title>Pets Care: turnos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     */}
      <Container maxWidth={'xl'} >
        <Box pt='80px'>
          <TitleSection title='turnos' colorLine='64C9A7' colorText='573469' />
          <Appointments />
        </Box>
      </Container>

    </>
  )
}

export default TurnosPage