import Head from 'next/head'
import Slider from '../components/home/carousel/Slider'
import Nosotros from '../components/home/nosotros'
import {Servicios}  from '../components/home/servicios/Servicios'
import { Ubicacion } from '../components/home/ubicacion/Ubicacion'
import { GetServerSideProps, GetStaticProps, NextPage } from 'next'
import { getServices } from '../services/stepperService'
import { Service } from '@/interfaces'

interface Props {
  services: Service[]
}


export default function Home({services}) {
  return (
    <>
      <Head>
        <title>Pets Care</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Slider />
        <Servicios services={services}/>
        <Nosotros/>
        <Ubicacion />
      </main>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async ({ res }) => {
  
  const services = await getServices()
 console.log(services);
  res.setHeader(
      'Cache-Control',
      'public, s-maxage=10, stale-while-revalidate'
  )
  return {
      props: {
          services
      }
  }
}
