import Head from 'next/head'
import Paper from '@mui/material/Paper'

export default function Home() {
  return (
    <>
      <Head>
        <title>Pets Care</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <Paper>
          <h1>hollla</h1>
        </Paper>
      </main>
    </>
  )
}
